### ISSUE TITLE
PyPi version missmatch

### ISSUE THREAD

**Issue by dev-239** [mnemonic-no/act-api-python#12]
The version of code in the master branch is not published to PyPi. Other dependencies, such as [act-bootstrap](https://github.com/mnemonic-no/act-bootstrap) will not work without the current code being published.

If the master branch is considered an unstable dev branch, perhaps tags should be implemented to convey the latest version that is considered stable. If not, any change to the version number in the master branch, could it be published to PyPi?

**Comment by frbor** [comment]
You are correct that the current master branch is not published to PyPi. We are currently looking into how we can make it easier to use compatible versions of backend, bootstrap, workers and python-api, howerver in the mean time I have pushed the latest version to PyPi so you will find 0.5.0 there now.
